const USER_FETCH_START = 'USER_FETCH_START';
const USER_FETCH_END = 'USER_FETCH_END';
const USER_SET_STATE = 'USER_SET_STATE';
const USER_RESET_STATE = 'USER_RESET_STATE';

const GLOBAL_FETCH_START = 'GLOBAL_FETCH_START';
const GLOBAL_FETCH_END = 'GLOBAL_FETCH_END';
const GLOBAL_SET_STATE = 'GLOBAL_SET_STATE';
const GLOBAL_RESET_STATE = 'GLOBAL_RESET_STATE';

const TRANSFER_FETCH_START = 'TRANSFER_FETCH_START';
const TRANSFER_FETCH_END = 'TRANSFER_FETCH_END';
const TRANSFER_SET_STATE = 'TRANSFER_SET_STATE';
const TRANSFER_RESET_STATE = 'TRANSFER_RESET_STATE';

const CONVERSION_FETCH_START = 'CONVERSION_FETCH_START';
const CONVERSION_FETCH_END = 'CONVERSION_FETCH_END';
const CONVERSION_SET_STATE = 'CONVERSION_SET_STATE';
const CONVERSION_RESET_STATE = 'CONVERSION_RESET_STATE';

export default {
  USER_FETCH_START,
  USER_FETCH_END,
  USER_SET_STATE,
  USER_RESET_STATE,
  GLOBAL_FETCH_START,
  GLOBAL_FETCH_END,
  GLOBAL_SET_STATE,
  GLOBAL_RESET_STATE,
  TRANSFER_FETCH_START,
  TRANSFER_FETCH_END,
  TRANSFER_SET_STATE,
  TRANSFER_RESET_STATE,
  CONVERSION_FETCH_START,
  CONVERSION_FETCH_END,
  CONVERSION_SET_STATE,
  CONVERSION_RESET_STATE,
};
